# name for the Workflow
name: Android Build by CI/CD

# Action which trigger this workflow
on: pull_request

# Jobs we want to perform every job will have it's own virtual machine
jobs:
  build:
    #Environment for running the Job
    runs-on: ubuntu-latest

    # Tasks we want to perform
    steps:
      # This step will checkout to current repo on current runnable file system
      - name: CheckOut
        uses: actions/checkout@v1

      # SetUp Java JDK
      - name: SetUp Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # SetUp Gradle for Linux
      - name: Gradle Executable
        run: chmod +x ./gradlew

      # Clean App
      - name: Clean Build
        run: ./gradlew clean --stacktrace

      # Test build
      - name: Run Test
        run: ./gradlew test

      # Build Project
      - name: Build Project
        run: ./gradlew assemble

      # Assemble Android Staging Apk
      - name: Satge Apk Assemble
        run: ./gradlew assembleAndroidStaging

      # Artifact for Staging Apk
      - name: Staging Apk Artifact
        uses: actions/uplaod-artifact@v1
        with:
          name: Staging Apk
          path: app/build/outputs/apk/android/staging/pp-android-staging-unsigned.apk



