name: Manual Generate APK
on:
  workflow_dispatch:

jobs:
  apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest

    # Tasks we want to perform
    steps:
      # This step will checkout to current repo on current runnable file system
      - name: CheckOut
        uses: actions/checkout@v1

      # SetUp Java JDK
      - name: SetUp Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # SetUp Gradle for Linux
      - name: Gradle Executable
        run: chmod +x ./gradlew

      # Clean App
      - name: Clean Build
        run: ./gradlew clean --stacktrace

      # Test build
      - name: Run Test
        run: ./gradlew test
