name: Manual Generate APK
on:
  workflow_dispatch:

    inputs:

      baseUrl:
        description: 'Base URL'
        required: true
        default: 'https://qa4.buynsta.com/'

      apiKey:
        description: 'Back End Base URL'
        required: true
        default: 'https://j8s51w4tyf.execute-api.ap-south-1.amazonaws.com/'

      gateway:
        description: 'App Gateway'
        required: true
        default: 'q4'

      appType:
        description: 'App Type'
        required: true
        default: 'android'

jobs:
  apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest

    # Tasks we want to perform
    steps:
      # This step will checkout to current repo on current runnable file system
      - name: CheckOut
        uses: actions/checkout@v1

      # SetUp Java JDK
      - name: SetUp Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # SetUp Gradle for Linux
      - name: Gradle Executable
        run: chmod +x ./gradlew

      # Clean App
      - name: Clean Build
        run: ./gradlew clean --stacktrace

      # Test build
      - name: Run Test
        run: ./gradlew test

      # Build Project
      - name: Build Project
        run: ./gradlew assemble

      # Assemble Debug Apk
      - name: Debug Apk Assemble
        run: ./gradlew assembleAndroidDebug

      # Artifact for Debug Apk
      - name: Debug Apk Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Debug Apk
          path: app/build/outputs/apk/android/debug/app-android-debug.apk
