# This is a basic workflow to help you get started with Actions

name: CI Manual

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  assemble_release:
    # The type of runner that the job will run on
    name: Runner Mac OS
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout current branch
        uses: actions/checkout@v2

      # Install JDK 11 tool for gradle
      - name: Instal JDK 11 for Gradle plugin
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Assemble APK
      - name: Assemble Release
        run: ./gradlew assembleRelease

      # Sign APK
      - name: Sign APP
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.RELEASE_ALIAS_KEY }}
          keyStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_ALIAS_PASSWORD }}

      # Upload Artifact
      - name: Artifact APK
      - uses: actions/upload-artifact@v2
        with:
          name: Signed Release APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}